/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponse } from '../../models/product-response';

export interface ApiProductsIdPut$Json$Params {
  id: number;
      body?: {
'Name'?: string;
'Description'?: string;
'Price'?: number;
'StockQuantity'?: number;
'IsActive'?: boolean;
'IsFeatured'?: boolean;
'CategoryId'?: number;
'ColorIds'?: Array<number>;
'NewImages'?: Array<Blob>;
'DeleteImageIds'?: Array<number>;
}
}

export function apiProductsIdPut$Json(http: HttpClient, rootUrl: string, params: ApiProductsIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProductsIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponse>;
    })
  );
}

apiProductsIdPut$Json.PATH = '/api/Products/{id}';
