/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponse } from '../../models/product-response';

export interface ApiProductsPost$Plain$Params {
      body?: {
'CategoryId'?: number;
'Name'?: string;
'Description'?: string;
'Price'?: number;
'StockQuantity'?: number;
'IsActive'?: boolean;
'IsFeatured'?: boolean;
'ColorIds'?: Array<number>;
'NewImages'?: Array<Blob>;
'DeleteImageIds'?: Array<number>;
}
}

export function apiProductsPost$Plain(http: HttpClient, rootUrl: string, params?: ApiProductsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProductsPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponse>;
    })
  );
}

apiProductsPost$Plain.PATH = '/api/Products';
