/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthResponse } from './models/auth-response';
export type { CategoryRequest } from './models/category-request';
export type { CategoryUpdateRequest } from './models/category-update-request';
export type { ColorRequest } from './models/color-request';
export type { ColorResponse } from './models/color-response';
export type { ColorUpdateRequest } from './models/color-update-request';
export type { GoogleLoginRequest } from './models/google-login-request';
export type { LoginRequest } from './models/login-request';
export type { ProductResponse } from './models/product-response';
export type { RegisterRequest } from './models/register-request';
export type { ReviewRequest } from './models/review-request';
export type { UserCreateRequest } from './models/user-create-request';
export type { UserResponse } from './models/user-response';
export type { UserUpdateRequest } from './models/user-update-request';
