/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponse } from '../../models/cart-response';

export interface ApiCartUserIdGet$Plain$Params {
  userId: number;
}

export function apiCartUserIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCartUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCartUserIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponse>;
    })
  );
}

apiCartUserIdGet$Plain.PATH = '/api/Cart/{userId}';
