/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartItemCreateRequest } from '../../models/cart-item-create-request';
import { CartItemResponse } from '../../models/cart-item-response';

export interface ApiCartUserIdPost$Json$Params {
  userId: number;
      body?: CartItemCreateRequest
}

export function apiCartUserIdPost$Json(http: HttpClient, rootUrl: string, params: ApiCartUserIdPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CartItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCartUserIdPost$Json.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartItemResponse>;
    })
  );
}

apiCartUserIdPost$Json.PATH = '/api/Cart/{userId}';
