/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartItemResponse } from '../../models/cart-item-response';

export interface ApiCartUserIdCartItemIdPut$Plain$Params {
  userId: number;
  cartItemId: number;
      body?: number
}

export function apiCartUserIdCartItemIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiCartUserIdCartItemIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CartItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCartUserIdCartItemIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('cartItemId', params.cartItemId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartItemResponse>;
    })
  );
}

apiCartUserIdCartItemIdPut$Plain.PATH = '/api/Cart/{userId}/{cartItemId}';
