/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  email?: string | null;
  name?: string | null;
  role?: string | null;
  token?: string | null;
  userId?: number;
}
