/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartItemCreateRequest {
  productId?: number;
  quantity?: number;
  variantId?: number | null;
}
