/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartItemResponse {
  cartItemId?: number;
  imageUrl?: string | null;
  price?: number;
  productId?: number;
  productName?: string | null;
  quantity?: number;
  variantName?: string | null;
}
