/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryRequest {
  description?: string | null;
  name?: string | null;
  parentId?: number | null;
}
