/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  brand?: string | null;
  categoryId?: number;
  color?: string | null;
  description?: string | null;
  dimensions?: string | null;
  imageUrls?: Array<string> | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  material?: string | null;
  name?: string | null;
  originCountry?: string | null;
  price?: number;
  productId?: number;
  stockQuantity?: number | null;
  warrantyMonths?: number | null;
  weight?: number | null;
}
