/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColorResponse } from '../models/color-response';
export interface ProductResponse {
  categoryId?: number;
  categoryName?: string | null;
  colors?: Array<ColorResponse> | null;
  description?: string | null;
  images?: Array<string> | null;
  isActive?: boolean;
  isFeatured?: boolean;
  name?: string | null;
  price?: number;
  productId?: number;
  stockQuantity?: number;
}
