/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  email?: string | null;
  isActive?: boolean;
  name?: string | null;
  password?: string | null;
  phone?: string | null;
}
