/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  address?: string | null;
  createdAt?: string | null;
  email?: string | null;
  isActive?: boolean | null;
  name?: string | null;
  phone?: string | null;
  role?: string | null;
  userId?: number;
}
