/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCategoryGet } from '../fn/category/api-category-get';
import { ApiCategoryGet$Params } from '../fn/category/api-category-get';
import { apiCategoryIdDelete } from '../fn/category/api-category-id-delete';
import { ApiCategoryIdDelete$Params } from '../fn/category/api-category-id-delete';
import { apiCategoryIdGet } from '../fn/category/api-category-id-get';
import { ApiCategoryIdGet$Params } from '../fn/category/api-category-id-get';
import { apiCategoryIdPut } from '../fn/category/api-category-id-put';
import { ApiCategoryIdPut$Params } from '../fn/category/api-category-id-put';
import { apiCategoryPost } from '../fn/category/api-category-post';
import { ApiCategoryPost$Params } from '../fn/category/api-category-post';

@Injectable({ providedIn: 'root' })
export class CategoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCategoryGet()` */
  static readonly ApiCategoryGetPath = '/api/Category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGet$Response(params?: ApiCategoryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCategoryGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGet(params?: ApiCategoryGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCategoryGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCategoryPost()` */
  static readonly ApiCategoryPostPath = '/api/Category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryPost$Response(params?: ApiCategoryPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCategoryPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryPost(params?: ApiCategoryPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCategoryPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCategoryIdGet()` */
  static readonly ApiCategoryIdGetPath = '/api/Category/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryIdGet$Response(params: ApiCategoryIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCategoryIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryIdGet(params: ApiCategoryIdGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCategoryIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCategoryIdPut()` */
  static readonly ApiCategoryIdPutPath = '/api/Category/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryIdPut$Response(params: ApiCategoryIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCategoryIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryIdPut(params: ApiCategoryIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiCategoryIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCategoryIdDelete()` */
  static readonly ApiCategoryIdDeletePath = '/api/Category/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryIdDelete$Response(params: ApiCategoryIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCategoryIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryIdDelete(params: ApiCategoryIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiCategoryIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
