/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiProductGet$Json } from '../fn/product/api-product-get-json';
import { ApiProductGet$Json$Params } from '../fn/product/api-product-get-json';
import { apiProductGet$Plain } from '../fn/product/api-product-get-plain';
import { ApiProductGet$Plain$Params } from '../fn/product/api-product-get-plain';
import { apiProductIdDelete } from '../fn/product/api-product-id-delete';
import { ApiProductIdDelete$Params } from '../fn/product/api-product-id-delete';
import { apiProductIdGet$Json } from '../fn/product/api-product-id-get-json';
import { ApiProductIdGet$Json$Params } from '../fn/product/api-product-id-get-json';
import { apiProductIdGet$Plain } from '../fn/product/api-product-id-get-plain';
import { ApiProductIdGet$Plain$Params } from '../fn/product/api-product-id-get-plain';
import { apiProductIdPut$Json } from '../fn/product/api-product-id-put-json';
import { ApiProductIdPut$Json$Params } from '../fn/product/api-product-id-put-json';
import { apiProductIdPut$Plain } from '../fn/product/api-product-id-put-plain';
import { ApiProductIdPut$Plain$Params } from '../fn/product/api-product-id-put-plain';
import { apiProductPost$Json } from '../fn/product/api-product-post-json';
import { ApiProductPost$Json$Params } from '../fn/product/api-product-post-json';
import { apiProductPost$Plain } from '../fn/product/api-product-post-plain';
import { ApiProductPost$Plain$Params } from '../fn/product/api-product-post-plain';
import { ProductResponse } from '../models/product-response';

@Injectable({ providedIn: 'root' })
export class ProductService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiProductGet()` */
  static readonly ApiProductGetPath = '/api/Product';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductGet$Plain$Response(params?: ApiProductGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductGet$Plain(params?: ApiProductGet$Plain$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductGet$Json$Response(params?: ApiProductGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductGet$Json(params?: ApiProductGet$Json$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `apiProductPost()` */
  static readonly ApiProductPostPath = '/api/Product';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductPost$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductPost$Plain$Response(params?: ApiProductPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductPost$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductPost$Plain(params?: ApiProductPost$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductPost$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductPost$Json$Response(params?: ApiProductPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductPost$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductPost$Json(params?: ApiProductPost$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductIdGet()` */
  static readonly ApiProductIdGetPath = '/api/Product/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdGet$Plain$Response(params: ApiProductIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdGet$Plain(params: ApiProductIdGet$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdGet$Json$Response(params: ApiProductIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdGet$Json(params: ApiProductIdGet$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductIdPut()` */
  static readonly ApiProductIdPutPath = '/api/Product/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductIdPut$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductIdPut$Plain$Response(params: ApiProductIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductIdPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductIdPut$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductIdPut$Plain(params: ApiProductIdPut$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductIdPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductIdPut$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductIdPut$Json$Response(params: ApiProductIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductIdPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductIdPut$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductIdPut$Json(params: ApiProductIdPut$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductIdPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductIdDelete()` */
  static readonly ApiProductIdDeletePath = '/api/Product/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdDelete$Response(params: ApiProductIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiProductIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductIdDelete(params: ApiProductIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiProductIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
