/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiProductsGet$Json } from '../fn/products/api-products-get-json';
import { ApiProductsGet$Json$Params } from '../fn/products/api-products-get-json';
import { apiProductsGet$Plain } from '../fn/products/api-products-get-plain';
import { ApiProductsGet$Plain$Params } from '../fn/products/api-products-get-plain';
import { apiProductsIdDelete } from '../fn/products/api-products-id-delete';
import { ApiProductsIdDelete$Params } from '../fn/products/api-products-id-delete';
import { apiProductsIdGet$Json } from '../fn/products/api-products-id-get-json';
import { ApiProductsIdGet$Json$Params } from '../fn/products/api-products-id-get-json';
import { apiProductsIdGet$Plain } from '../fn/products/api-products-id-get-plain';
import { ApiProductsIdGet$Plain$Params } from '../fn/products/api-products-id-get-plain';
import { apiProductsIdPut$Json } from '../fn/products/api-products-id-put-json';
import { ApiProductsIdPut$Json$Params } from '../fn/products/api-products-id-put-json';
import { apiProductsIdPut$Plain } from '../fn/products/api-products-id-put-plain';
import { ApiProductsIdPut$Plain$Params } from '../fn/products/api-products-id-put-plain';
import { apiProductsIdToggleActivePatch$Json } from '../fn/products/api-products-id-toggle-active-patch-json';
import { ApiProductsIdToggleActivePatch$Json$Params } from '../fn/products/api-products-id-toggle-active-patch-json';
import { apiProductsIdToggleActivePatch$Plain } from '../fn/products/api-products-id-toggle-active-patch-plain';
import { ApiProductsIdToggleActivePatch$Plain$Params } from '../fn/products/api-products-id-toggle-active-patch-plain';
import { apiProductsIdToggleFeaturedPatch$Json } from '../fn/products/api-products-id-toggle-featured-patch-json';
import { ApiProductsIdToggleFeaturedPatch$Json$Params } from '../fn/products/api-products-id-toggle-featured-patch-json';
import { apiProductsIdToggleFeaturedPatch$Plain } from '../fn/products/api-products-id-toggle-featured-patch-plain';
import { ApiProductsIdToggleFeaturedPatch$Plain$Params } from '../fn/products/api-products-id-toggle-featured-patch-plain';
import { apiProductsPost$Json } from '../fn/products/api-products-post-json';
import { ApiProductsPost$Json$Params } from '../fn/products/api-products-post-json';
import { apiProductsPost$Plain } from '../fn/products/api-products-post-plain';
import { ApiProductsPost$Plain$Params } from '../fn/products/api-products-post-plain';
import { apiProductsSearchGet$Json } from '../fn/products/api-products-search-get-json';
import { ApiProductsSearchGet$Json$Params } from '../fn/products/api-products-search-get-json';
import { apiProductsSearchGet$Plain } from '../fn/products/api-products-search-get-plain';
import { ApiProductsSearchGet$Plain$Params } from '../fn/products/api-products-search-get-plain';
import { ProductResponse } from '../models/product-response';

@Injectable({ providedIn: 'root' })
export class ProductsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiProductsGet()` */
  static readonly ApiProductsGetPath = '/api/Products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsGet$Plain$Response(params?: ApiProductsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsGet$Plain(params?: ApiProductsGet$Plain$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsGet$Json$Response(params?: ApiProductsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsGet$Json(params?: ApiProductsGet$Json$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `apiProductsPost()` */
  static readonly ApiProductsPostPath = '/api/Products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsPost$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsPost$Plain$Response(params?: ApiProductsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsPost$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsPost$Plain(params?: ApiProductsPost$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsPost$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsPost$Json$Response(params?: ApiProductsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsPost$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsPost$Json(params?: ApiProductsPost$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductsIdGet()` */
  static readonly ApiProductsIdGetPath = '/api/Products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdGet$Plain$Response(params: ApiProductsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdGet$Plain(params: ApiProductsIdGet$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdGet$Json$Response(params: ApiProductsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdGet$Json(params: ApiProductsIdGet$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductsIdPut()` */
  static readonly ApiProductsIdPutPath = '/api/Products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdPut$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsIdPut$Plain$Response(params: ApiProductsIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdPut$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsIdPut$Plain(params: ApiProductsIdPut$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdPut$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsIdPut$Json$Response(params: ApiProductsIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdPut$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiProductsIdPut$Json(params: ApiProductsIdPut$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductsIdDelete()` */
  static readonly ApiProductsIdDeletePath = '/api/Products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdDelete$Response(params: ApiProductsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiProductsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdDelete(params: ApiProductsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiProductsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiProductsSearchGet()` */
  static readonly ApiProductsSearchGetPath = '/api/Products/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsSearchGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsSearchGet$Plain$Response(params?: ApiProductsSearchGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductsSearchGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsSearchGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsSearchGet$Plain(params?: ApiProductsSearchGet$Plain$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductsSearchGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsSearchGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsSearchGet$Json$Response(params?: ApiProductsSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return apiProductsSearchGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsSearchGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsSearchGet$Json(params?: ApiProductsSearchGet$Json$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.apiProductsSearchGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `apiProductsIdToggleFeaturedPatch()` */
  static readonly ApiProductsIdToggleFeaturedPatchPath = '/api/Products/{id}/toggle-featured';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdToggleFeaturedPatch$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleFeaturedPatch$Plain$Response(params: ApiProductsIdToggleFeaturedPatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdToggleFeaturedPatch$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdToggleFeaturedPatch$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleFeaturedPatch$Plain(params: ApiProductsIdToggleFeaturedPatch$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdToggleFeaturedPatch$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdToggleFeaturedPatch$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleFeaturedPatch$Json$Response(params: ApiProductsIdToggleFeaturedPatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdToggleFeaturedPatch$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdToggleFeaturedPatch$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleFeaturedPatch$Json(params: ApiProductsIdToggleFeaturedPatch$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdToggleFeaturedPatch$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `apiProductsIdToggleActivePatch()` */
  static readonly ApiProductsIdToggleActivePatchPath = '/api/Products/{id}/toggle-active';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdToggleActivePatch$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleActivePatch$Plain$Response(params: ApiProductsIdToggleActivePatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdToggleActivePatch$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdToggleActivePatch$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleActivePatch$Plain(params: ApiProductsIdToggleActivePatch$Plain$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdToggleActivePatch$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsIdToggleActivePatch$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleActivePatch$Json$Response(params: ApiProductsIdToggleActivePatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return apiProductsIdToggleActivePatch$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsIdToggleActivePatch$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsIdToggleActivePatch$Json(params: ApiProductsIdToggleActivePatch$Json$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.apiProductsIdToggleActivePatch$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

}
