/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserGet$Json } from '../fn/user/api-user-get-json';
import { ApiUserGet$Json$Params } from '../fn/user/api-user-get-json';
import { apiUserGet$Plain } from '../fn/user/api-user-get-plain';
import { ApiUserGet$Plain$Params } from '../fn/user/api-user-get-plain';
import { apiUserIdChangeActivePatch$Json } from '../fn/user/api-user-id-change-active-patch-json';
import { ApiUserIdChangeActivePatch$Json$Params } from '../fn/user/api-user-id-change-active-patch-json';
import { apiUserIdChangeActivePatch$Plain } from '../fn/user/api-user-id-change-active-patch-plain';
import { ApiUserIdChangeActivePatch$Plain$Params } from '../fn/user/api-user-id-change-active-patch-plain';
import { apiUserIdDelete } from '../fn/user/api-user-id-delete';
import { ApiUserIdDelete$Params } from '../fn/user/api-user-id-delete';
import { apiUserIdGet$Json } from '../fn/user/api-user-id-get-json';
import { ApiUserIdGet$Json$Params } from '../fn/user/api-user-id-get-json';
import { apiUserIdGet$Plain } from '../fn/user/api-user-id-get-plain';
import { ApiUserIdGet$Plain$Params } from '../fn/user/api-user-id-get-plain';
import { apiUserIdPut$Json } from '../fn/user/api-user-id-put-json';
import { ApiUserIdPut$Json$Params } from '../fn/user/api-user-id-put-json';
import { apiUserIdPut$Plain } from '../fn/user/api-user-id-put-plain';
import { ApiUserIdPut$Plain$Params } from '../fn/user/api-user-id-put-plain';
import { apiUserPost$Json } from '../fn/user/api-user-post-json';
import { ApiUserPost$Json$Params } from '../fn/user/api-user-post-json';
import { apiUserPost$Plain } from '../fn/user/api-user-post-plain';
import { ApiUserPost$Plain$Params } from '../fn/user/api-user-post-plain';
import { apiUserSearchGet$Json } from '../fn/user/api-user-search-get-json';
import { ApiUserSearchGet$Json$Params } from '../fn/user/api-user-search-get-json';
import { apiUserSearchGet$Plain } from '../fn/user/api-user-search-get-plain';
import { ApiUserSearchGet$Plain$Params } from '../fn/user/api-user-search-get-plain';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserGet()` */
  static readonly ApiUserGetPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Plain$Response(params?: ApiUserGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponse>>> {
    return apiUserGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Plain(params?: ApiUserGet$Plain$Params, context?: HttpContext): Observable<Array<UserResponse>> {
    return this.apiUserGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Json$Response(params?: ApiUserGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponse>>> {
    return apiUserGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Json(params?: ApiUserGet$Json$Params, context?: HttpContext): Observable<Array<UserResponse>> {
    return this.apiUserGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body)
    );
  }

  /** Path part for operation `apiUserPost()` */
  static readonly ApiUserPostPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Plain$Response(params?: ApiUserPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Plain(params?: ApiUserPost$Plain$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Json$Response(params?: ApiUserPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Json(params?: ApiUserPost$Json$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `apiUserIdGet()` */
  static readonly ApiUserIdGetPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Plain$Response(params: ApiUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Plain(params: ApiUserIdGet$Plain$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Json$Response(params: ApiUserIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Json(params: ApiUserIdGet$Json$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `apiUserIdPut()` */
  static readonly ApiUserIdPutPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Plain$Response(params: ApiUserIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Plain(params: ApiUserIdPut$Plain$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Json$Response(params: ApiUserIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Json(params: ApiUserIdPut$Json$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `apiUserIdDelete()` */
  static readonly ApiUserIdDeletePath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdDelete$Response(params: ApiUserIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdDelete(params: ApiUserIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiUserIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserSearchGet()` */
  static readonly ApiUserSearchGetPath = '/api/User/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserSearchGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet$Plain$Response(params?: ApiUserSearchGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponse>>> {
    return apiUserSearchGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserSearchGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet$Plain(params?: ApiUserSearchGet$Plain$Params, context?: HttpContext): Observable<Array<UserResponse>> {
    return this.apiUserSearchGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserSearchGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet$Json$Response(params?: ApiUserSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponse>>> {
    return apiUserSearchGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserSearchGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet$Json(params?: ApiUserSearchGet$Json$Params, context?: HttpContext): Observable<Array<UserResponse>> {
    return this.apiUserSearchGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body)
    );
  }

  /** Path part for operation `apiUserIdChangeActivePatch()` */
  static readonly ApiUserIdChangeActivePatchPath = '/api/User/{id}/change-active';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdChangeActivePatch$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdChangeActivePatch$Plain$Response(params: ApiUserIdChangeActivePatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdChangeActivePatch$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdChangeActivePatch$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdChangeActivePatch$Plain(params: ApiUserIdChangeActivePatch$Plain$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdChangeActivePatch$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdChangeActivePatch$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdChangeActivePatch$Json$Response(params: ApiUserIdChangeActivePatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return apiUserIdChangeActivePatch$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdChangeActivePatch$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdChangeActivePatch$Json(params: ApiUserIdChangeActivePatch$Json$Params, context?: HttpContext): Observable<UserResponse> {
    return this.apiUserIdChangeActivePatch$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

}
