/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponse } from '../../models/product-response';

export interface ApiProductPost$Json$Params {
      body?: {
'CategoryId'?: number;
'Name'?: string;
'Description'?: string;
'Price'?: number;
'Brand'?: string;
'Material'?: string;
'Color'?: string;
'StockQuantity'?: number;
'Dimensions'?: string;
'Weight'?: number;
'WarrantyMonths'?: number;
'OriginCountry'?: string;
'IsFeatured'?: boolean;
'IsActive'?: boolean;
'Images'?: Array<Blob>;
}
}

export function apiProductPost$Json(http: HttpClient, rootUrl: string, params?: ApiProductPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProductPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponse>;
    })
  );
}

apiProductPost$Json.PATH = '/api/Product';
